def help_option():

	print ('                       ---HELP---                       ')
	print ('========================================================')
	print ('All time recorded is in represented in the UTC timezone.')
	print (' ')
	print ('[1] Active users option: Gives a display of all active  ')
	print ('users currently logged on. Active users are             ')
	print ('defined as users that have shown activity in the past   ')
	print ('minute.                                                 ')
	print ('Data is updated every minute')
	print (' ')
	print (' ')
	print ('[2] Idle Users: Gives a list of all the idle users      ')
	print ('currently logged into the system. Idle users are        ')
	print ('defined as users that have not been active for more     ')
	print ('than a minute.                                          ')
	print ('Data is updated every minute')
	print (' ')
	print (' ')
	print ('[3] Offline Users: Displays a list of all users that are')
	print ('currently offline. It will also display the last login  ')
	print ('time and date of each of the offline user               ')
	print ('Data is updated every minute')
	print (' ')
	print (' ')
	print ('[4] Usage History: Displays all the times users logged  ')
	print ('in and logged off during a day grouped by user. Will    ')
	print ('also display the total amount of time logged in by a    ')
	print ('singular user and the total time logged during the day. ')
	print ('Data is updated every day at 12:01 AM UTC')
	print (' ')
	print (' ')
	print ('[5] Summary: Gives a summary of options 1-3 in a table ')
	print ('format.                                                ')
	print (' ')
	print ('QATWatch was written in a joint effort among six       ')
	print ('individuals                                            ')
	print ('David Avila')
	print ('Cassie Jeon')
	print ('Takara Larsen')
	print ('Alana Martin')
	print ('Jennifer Meggs')
	print ('Christianna Vasquez')
	print (' ')
	return()







